# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      steps:
      - uses: actions/checkout@v4
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          DB_URL: 'postgres://postgres:postgres@localhost:5432/postgres'
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
  
      - name: Build
        run: go build -v ./...

    - name: Test
      run: go test -v ./...
